name: .NET in the Trenches
description: Harvey Kandola - .NET in the Trenches

url: http://www.collectivematters.com
auto: true
permalink: /:year/:month/:title
exclude: [server, misc]
safe: false

source:      ./_source
destination: ./website
