name: .NET in the Trenches
description: Harvey Kandola - .NET in the Trenches

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog 

url: http://www.collectivematters.com

auto: true

permalink: /:year/:month/:title

exclude: [server, misc]

safe: false

source:      .
destination: ./_site
plugins:     ./_plugins
